### ISSUE TITLE
Not all `property`s that are being set in `climate.py` show up as attributes in homeassistant

### ISSUE THREAD

**Issue by jetpacktuxedo** [bm1549/home-assistant-frigidaire#6]
Here are the attributes that I am seeing in homeassistant right now (`homeassistant` `2021.8.6,` `home-assistant-frigidaire` `f717fa6b6597da59ba55b6285f4846e1b183771d`):
```yaml
hvac_modes:
  - 'off'
  - cool
  - auto
  - fan_only
min_temp: 60
max_temp: 90
target_temp_step: 1
fan_modes:
  - auto
  - low
  - medium
  - high
current_temperature: 75
temperature: 60
fan_mode: low
friendly_name: Window AC
assumed_state: true
supported_features: 9
```

notably this appears to be missing [`hvac_mode`](https://github.com/bm1549/home-assistant-frigidaire/blob/main/custom_components/frigidaire/climate.py#L148-L162) even though it is defined in what appears to be the same way as [`fan mode`](https://github.com/bm1549/home-assistant-frigidaire/blob/main/custom_components/frigidaire/climate.py#L173-L188) which does appear in the list.

I'm happy to fix this myself and PR it up, I just can't for the life of me figure out why it doesn't show up at all.
